### PR TITLE
fix: set CORS header for `get_pdf_file` endpoint

### PR DESCRIPTION
**Pull request by SebastianKohler**
Three changes:

1. Dynamically set the Access-Control-Allow-Origin header to the request origin if the origin is a *.sls.fi subdomain. This makes it possible to embed PDFs served by the API on these sites. For example, In the new frontend of granqvist.sls.fi PDF books are embedded in the web page. Currently the browser blocks these PDFs from being displayed embedded because of the lack of a Access-Control-Allow-Origin header in the response from api.sls.fi.

This is just a suggested fix, there might be a better solution. Currently the main domain "sls.fi" is hard-coded as an allowed origin, but it would be better if the allowed domain(s) would be read from the config.

3. Refactor if-elif code block setting `file_path` so there is only one branch per file type, and explicitly add mimetype to `send_file`.

4. Place the `connection.close()` call within a `finally` block to ensure connection closure on early returns.

### CODE REVIEW

**Comment by SebastianKohler** [comment]
As a side note:

One problem with the endpoint's code that I haven't fixed is that pdf and epub file types are treated differently. `<use_download_name>` can't be used for epubs, which means that the epub files in the backend always have to have the filename `<collection_id>.epub`, whereas pdfs can have any filenames.

**Review by rasek-sls — CHANGES_REQUESTED** [review]
In general, this code looks good. But I agree that sls.fi should not be hardcoded.
It would be better to add something like a get_allowed_origins() method to `generics.py` and return a value from the config file in that method.

That way, the allowed origin can be stored in the configuration file, and retrieved from there using the existing in-memory data that `generics.py` already reads on API startup.

**Comment by SebastianKohler** [comment]
I modified the code so allowed origins are defined in a list with the key `allowed_cors_origins` in the project sections of the config YAML file.

The code is backwards compatible with config files where the `allowed_cors_origins` key is missing in project sections.

**Review by rasek-sls — APPROVED** [review]
Looks good to me!

**Pull request merged**
